server:
  port: 8083
spring:
  application:
    name: all-consumer
feign:
  httpclient:
    enabled: true  #使用httpclient
  hystrix:
    enabled: true  #开启容错
hystrix:
  command:
    "PersonFeignClient#person()": #直接在配置文件配置部分
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 500    
      circuitBreaker:
        requestVolumeThreshold: 3 
all-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.zda.consumer.ribbonRule.MyRule #com.netflix.loadbalancer.RandomRule   #负载均衡策略，如果没有写的话会默认使用循环
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/